/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pengelolaan_Buku;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Destroy Eyes
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String c1;

    public String getC1() {
        return c1;
    }

    public void setC1(String c1) {
        this.c1 = c1;
    }
    
    int mousepX;
    int mousepY;
    public Home() {
        initComponents();
        populateJtble();
        BindCombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 156, 18), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(243, 156, 18));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(243, 180, 18));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pengelolaan_Buku/image/minus-sign-of-a-line-in-horizontal-position (1).png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 3, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 40, 30));

        jPanel8.setBackground(new java.awt.Color(243, 180, 18));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pengelolaan_Buku/image/cross-remove-sign.png"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 7, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        jPanel3.setBackground(new java.awt.Color(243, 180, 18));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Data Information");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 810, 5));

        jPanel6.setBackground(new java.awt.Color(243, 156, 18));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pengelolaan_Buku/image/user.png"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 5, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 39, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1112, 15, 60, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 90));

        jPanel4.setBackground(new java.awt.Color(243, 156, 18));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1200, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, 1176, 445));
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 183, 168, 27));

        jPanel9.setBackground(new java.awt.Color(243, 180, 18));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel9MouseReleased(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pengelolaan_Buku/image/searching-magnifying-glass (1).png"))); // NOI18N
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 183, 27, 27));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 183, 173, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(218,131,0));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:255  182  44
        jPanel6.setBackground(new Color(243,156,18));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(255,182,44));
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
         jPanel6.setBackground(new Color(218,131,0));
    }//GEN-LAST:event_jPanel6MouseReleased

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(243,180,18));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(218,115,0));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
         jPanel7.setBackground(new Color(243,180,18));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(218,115,0));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(243,180,18));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(255,206,44));
        ArrayList<Buku> list = BindTableSearchHome();
        String[] columnName = {"KODE","JUDUL BUKU","PENGARANG","TAHUN TERBIT","LOKASI BUKU","GAMBAR","PENERBIT","KATEGORI"};
        Object[][] rows = new Object[list.size()][8];
        for (int i = 0; i < list.size(); i++){
            rows[i][0]=list.get(i).getKodeBuku();
            rows[i][1]=list.get(i).getJudulBuku();
            rows[i][2]=list.get(i).getPengarang();
            rows[i][3]=list.get(i).getThnTerbit();
            rows[i][4]=list.get(i).getLokasi();
            
            if(list.get(i).getGambar() != null){
                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getGambar()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
                
                rows[i][5] = image;
            }else{
                rows[i][5] = null;
//rows[i][5]=list.get(i).getGambar();
            }
            
            rows[i][6]=list.get(i).getPenerbit();
            rows[i][7]=list.get(i).getKategori();
        }
        TheModel model = new TheModel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        search.setText("");
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseReleased
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(218,115,0));
    }//GEN-LAST:event_jPanel9MouseReleased

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
         mousepX = evt.getX();
       mousepY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jPanel7MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        HashMap<String, Integer> map = populateCombo2();
        setC1(map.get(jComboBox1.getSelectedItem().toString()).toString());
       
         ArrayList<Buku> list = BindTableCategory();
        String[] columnName = {"KODE","JUDUL BUKU","PENGARANG","TAHUN TERBIT","LOKASI BUKU","GAMBAR","PENERBIT","KATEGORI"};
        Object[][] rows = new Object[list.size()][8];
        for (int i = 0; i < list.size(); i++){
            rows[i][0]=list.get(i).getKodeBuku();
            rows[i][1]=list.get(i).getJudulBuku();
            rows[i][2]=list.get(i).getPengarang();
            rows[i][3]=list.get(i).getThnTerbit();
            rows[i][4]=list.get(i).getLokasi();
            
            if(list.get(i).getGambar() != null){
                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getGambar()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
                
                rows[i][5] = image;
            }else{
                rows[i][5] = null;
//rows[i][5]=list.get(i).getGambar();
            }
            
            rows[i][6]=list.get(i).getPenerbit();
            rows[i][7]=list.get(i).getKategori();
        }
        TheModel model = new TheModel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
private ArrayList<Buku> BindTable() {
        ArrayList<Buku> list = new ArrayList<Buku>();
        try {
            Connection cn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbbuku","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT kode_buku,judul_buku,pengarang,tahun_terbit,lokasi_buku,gambar,nama_penerbit,nama_kategori from buku,penerbit,kategori WHERE buku.kode_penerbit=penerbit.kode_penerbit AND buku.kode_kategori=kategori.kode_kategori ORDER BY kode_buku ASC"); 
            Buku p;
            while (rs.next()){
                p = new Buku(
                        rs.getString("kode_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getInt("tahun_terbit"),
                        rs.getString("lokasi_buku"),
                        rs.getBytes("gambar"),
                        rs.getString("nama_penerbit"),
                        rs.getString("nama_kategori")
                );
            list.add(p);    
            }
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return list;
    }
private ArrayList<Buku> BindTableSearchHome() {
        ArrayList<Buku> list = new ArrayList<Buku>();
        try {
            Connection cn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbbuku","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT kode_buku,judul_buku,pengarang,tahun_terbit,lokasi_buku,gambar,nama_penerbit,nama_kategori from buku,penerbit,kategori WHERE buku.kode_penerbit=penerbit.kode_penerbit AND buku.kode_kategori=kategori.kode_kategori AND buku.judul_buku like '%"+search.getText()+"%' ORDER BY kode_buku ASC"); 
            Buku p;
            while (rs.next()){
                p = new Buku(
                        rs.getString("kode_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getInt("tahun_terbit"),
                        rs.getString("lokasi_buku"),
                        rs.getBytes("gambar"),
                        rs.getString("nama_penerbit"),
                        rs.getString("nama_kategori")
                );
            list.add(p);    
            }
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return list;
    }
private ArrayList<Buku> BindTableCategory() {
        ArrayList<Buku> list = new ArrayList<Buku>();
        try {
            Connection cn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbbuku","root","");
            if (jComboBox1.getSelectedItem().equals("All")){
                ResultSet rs = cn.createStatement().executeQuery("SELECT kode_buku,judul_buku,pengarang,tahun_terbit,lokasi_buku,gambar,nama_penerbit,nama_kategori from buku,penerbit,kategori WHERE buku.kode_penerbit=penerbit.kode_penerbit AND buku.kode_kategori=kategori.kode_kategori ORDER BY kode_buku ASC"); 
            Buku p;
            while (rs.next()){ 
                p = new Buku(
                        rs.getString("kode_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getInt("tahun_terbit"),
                        rs.getString("lokasi_buku"),
                        rs.getBytes("gambar"),
                        rs.getString("nama_penerbit"),
                        rs.getString("nama_kategori")
                );
            list.add(p);    
            }
            } else {
            ResultSet rs = cn.createStatement().executeQuery("SELECT kode_buku,judul_buku,pengarang,tahun_terbit,lokasi_buku,gambar,nama_penerbit,nama_kategori from buku,penerbit,kategori WHERE buku.kode_penerbit=penerbit.kode_penerbit AND buku.kode_kategori=kategori.kode_kategori AND buku.kode_kategori='"+getC1()+"' ORDER BY kode_buku ASC"); 
            Buku p;
            while (rs.next()){
                p = new Buku(
                        rs.getString("kode_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getInt("tahun_terbit"),
                        rs.getString("lokasi_buku"),
                        rs.getBytes("gambar"),
                        rs.getString("nama_penerbit"),
                        rs.getString("nama_kategori")
                );
            list.add(p);    
            }
            }
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return list;
    }
public void populateJtble(){
        ArrayList<Buku> list = BindTable();
        String[] columnName = {"KODE","JUDUL BUKU","PENGARANG","TAHUN TERBIT","LOKASI BUKU","GAMBAR","PENERBIT","KATEGORI"};
        Object[][] rows = new Object[list.size()][8];
        for (int i = 0; i < list.size(); i++){
            rows[i][0]=list.get(i).getKodeBuku();
            rows[i][1]=list.get(i).getJudulBuku();
            rows[i][2]=list.get(i).getPengarang();
            rows[i][3]=list.get(i).getThnTerbit();
            rows[i][4]=list.get(i).getLokasi();
            
            if(list.get(i).getGambar() != null){
                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getGambar()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
                
                rows[i][5] = image;
            }else{
                rows[i][5] = null;
//rows[i][5]=list.get(i).getGambar();
            }
            
            rows[i][6]=list.get(i).getPenerbit();
            rows[i][7]=list.get(i).getKategori();
        }
        TheModel model = new TheModel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
       
    }
public HashMap<String, Integer> populateCombo2(){
         HashMap<String, Integer> map = new HashMap<String, Integer>();
         try {
            Connection cn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbbuku","root","");
            ResultSet rs = cn.createStatement().executeQuery("select kode_kategori,nama_kategori from kategori"); 
            ComboItem cmi;
            while (rs.next()){
                cmi = new ComboItem(rs.getInt(1),rs.getString(2));
                map.put(cmi.getNama(), cmi.getKode());
            }
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
         return map;
    }
public void BindCombo2(){
        //Admin mq = new Admin();
        HashMap<String, Integer> map = populateCombo2();
        for (String s : map.keySet()){
            jComboBox1.addItem(s);
        }
    }
}
